name: Always Pass Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pass:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Always pass step
        run: |
          echo "This step always passes"
          exit 0
