            - name: Run tsc with reviewdog
  # You may pin to the exact commit or the version.
  # uses: EPMatt/reviewdog-action-tsc@935b711379c6435deadfc92c14c66e40aaf8eb79
  uses: EPMatt/reviewdog-action-tsc@v1.3.0
  with:
    # GITHUB_TOKEN
    github_token: # optional, default is ${{ github.token }}
    # Working directory relative to the root directory.
This is where the action will look for a
package.json which declares typescript as a dependency.
Default is `.`.

    workdir: # optional, default is .
    # Report level for reviewdog [info,warning,error].
Default is `error`.

    level: # optional, default is error
    # Reporter of reviewdog command [github-pr-check,github-pr-review].
Default is `github-pr-check`.

    reporter: # optional, default is github-pr-check
    # Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
Default is `added`.

    filter_mode: # optional, default is added
    # Exit code for reviewdog when errors are found [true,false].
Default is `false`.

    fail_on_error: # optional, default is false
    # Additional reviewdog flags.
Default is ``.

    reviewdog_flags: # optional, default is 
    # Tool name to use for reviewdog reporter
    tool_name: # optional, default is tsc
    # Flags and args to pass to tsc.
Default is ``.

    tsc_flags: # optional, default is 
          
